name: EC2 CI-CD Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  clone:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  build_test_scan:
    runs-on: self-hosted
    needs: clone
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test || echo "No tests found"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=SaimShaikh_emoji_hunter
            -Dsonar.organization=saimshaikh
            -Dsonar.sources=src

  docker_build_scan_push:
    runs-on: self-hosted
    needs: build_test_scan
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t emoji_hunter:latest .

      - name: Trivy Scan (local image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: emoji_hunter:latest
          severity: HIGH,CRITICAL
          exit-code: 0   # ðŸ”´ change to 1 when you want strict security
          format: table

      - name: Tag Docker image
        run: docker tag emoji_hunter:latest ${{ secrets.DOCKERHUB_USERNAME }}/emoji_hunter:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/emoji_hunter:latest

  deploy:
    runs-on: self-hosted
    needs: docker_build_scan_push
    steps:
      - name: Stop old container
        run: |
          docker stop emoji_hunter || true
          docker rm emoji_hunter || true

      - name: Run new container
        run: |
          docker run -d \
            --name emoji_hunter \
            -p 80:5173 \
            ${{ secrets.DOCKERHUB_USERNAME }}/emoji_hunter:latest
