name: EC2 CI-CD Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  clone:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

  build_test_scan:
    runs-on: self-hosted
    needs: clone
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm test || echo "No tests found"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=SaimShaikh_emoji_hunter
            -Dsonar.organization=saimshaikh
            -Dsonar.sources=src

  docker_build_scan_push:
    runs-on: self-hosted
    needs: build_test_scan
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build -t emoji_hunter:latest .

      - name: Tag image
        run: docker tag emoji_hunter:latest ${{ secrets.DOCKERHUB_USERNAME }}/emoji_hunter:latest

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.65.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/emoji_hunter:latest
          severity: HIGH,CRITICAL
          exit-code: 1
          format: table
      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/emoji_hunter:latest

  deploy:
    runs-on: self-hosted
    needs: docker_build_scan_push
    steps:
      - run: docker stop emoji_hunter || true
      - run: docker rm emoji_hunter || true
      - run: |
          docker run -d \
            --name emoji_hunter \
            -p 80:5173 \
            ${{ secrets.DOCKERHUB_USERNAME }}/emoji_hunter:latest
